# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-ast
  - id: check-yaml
  - id: check-added-large-files
  - id: check-case-conflict     # Check for files that would conflict in case-insensitive filesystems
  - id: check-merge-conflict     # Check for files that contain merge conflict strings.
  - id: debug-statements     # Check for debugger imports and py37+ `breakpoint()` calls in python source.
  - id: requirements-txt-fixer     # Sorts entries in requirements.txt
  - id: forbid-new-submodules     # Check for git submodules

- repo: https://github.com/asottile/seed-isort-config
  rev: v2.2.0
  hooks:
  - id: seed-isort-config

- repo: https://github.com/timothycrosley/isort
  rev: 5.9.3   # pick the isort version you'd like to use from https://github.com/timothycrosley/isort/releases
  hooks:
  - id: isort

- repo: https://github.com/asottile/blacken-docs
  rev: v1.11.0
  hooks:
  - id: blacken-docs
    additional_dependencies: [black]

- repo: https://github.com/psf/black
  rev: 21.9b0
  hooks:
  - id: black

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910-1
  hooks:
  - id: mypy
    exclude: tests/
    additional_dependencies: [types-cachetools]

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8

- repo: https://github.com/pycqa/pylint
  rev: v2.11.1
  hooks:
  - id: pylint

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.2.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']

- repo: https://gitlab.com/smop/pre-commit-hooks
  rev: v1.0.0
  hooks:
  - id: check-poetry
